language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - "8"
  - "10"
  - "12"
services:
  - mongodb
branches:
  only:
    - master
env:
  - NODE_ENV=test PORT=3000 MONGO_URI=mongodb://localhost/torchexpo HEADERS_ACCEPT=application/vnd.torchexpo+json;version=1
script: npm run validate
after_success: npm run coverage